In [ ]:
# Task 01:

import numpy as np

x1=np.random.randint(10, size=10)

x2=np.random.randint(10, size=(7,6))

print(x1)


[7 7 6 4 1 7 1 0 5 6]
[[1 1 2 8 8 5]
 [1 9 4 5 7 3]
 [1 7 6 0 9 2]
 [7 4 5 4 9 9]
 [3 8 8 9 8 4]
 [1 9 8 0 7 1]
 [9 0 2 5 5 5]]
[[1 1 2 8 8 5 1 9 4 5 7 3 1 7]
 [6 0 9 2 7 4 5 4 9 9 3 8 8 9]
 [8 4 1 9 8 0 7 1 9 0 2 5 5 5]]


In [ ]:
# Task 02:

x2=np.random.randint(10, size=(7,6))

print(x2)

x3=x2.reshape(3,14)

print(x3)


In [ ]:
# Task 03:

import numpy as np
x4 = np.array([0,1,2,3,4,5,6,7,8,9])
x4[x4 % 2 == 1]

array([1, 3, 5, 7, 9])

In [ ]:
# Task 04:

import numpy as np
x4 = np.array([0,1,2,3,4,5,6,7,8,9])
x4[x4 % 2 == 1]
x4[x4%2 == 1] = -1 
print(x4)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# Task 05:

import numpy as np
x4 = np.array([0,1,2,3,4,5,6,7,8,9])
x5 = x4.copy()
x5[x5 % 2 == 1]
x5[x5%2 == 1] = -1 
print(x4)
print(x5)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# Task 06:

a1 = np.array([1,2,3,2,3,4,3,4,5,6])
b1= np.array([7,2,10,2,7,4,9,4,9,8])
x11=np.where(a1==b1)
print(x11)

(array([1, 3, 5, 7]),)


In [ ]:
# Task 07:

a = np.array([2, 6, 1, 9, 10, 3, 27])
b=np.where((a >= 5) & (a <= 10))
print(a[b])

[ 6  9 10]


In [ ]:
# Task 08:

a=np.zeros(10)
b=np.ones(10)
print(a)
print(b)
c=np.concatenate([a,b])
print(c)

d = a.reshape(10,1)
print(d)
e = b.reshape(10,1)
print(e)
f=np.concatenate([d,e])
print(f)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
# Task 09:

x=np.random.randint(10, size=(5,4))
print(x)

[[6 3 7 9]
 [0 8 8 1]
 [6 0 0 1]
 [2 8 7 6]
 [0 5 9 8]]


In [ ]:
# Task 10:

import numpy as np

x = np.random.rand(5, 4)
y = np.random.randint( 0, 2, 5)

print('x = \n', x)
print('y = \n', y)

x = 
 [[0.26893494 0.17405219 0.98140853 0.18303019]
 [0.9108853  0.48133887 0.66856907 0.80474451]
 [0.53649822 0.0512162  0.70431021 0.46631163]
 [0.67850822 0.98170513 0.63654161 0.9521077 ]
 [0.14003157 0.01730821 0.23235055 0.88072912]]
y = 
 [0 1 0 0 1]


In [ ]:
# Task 11:

def extract_subset(x, y, y0):
    return x[y==y0, :]

x = np.random.rand(5, 4)
y = np.random.randint(0, 2, 5)

y0 = 0
x0 = extract_subset(x, y, y0)

print('x: \n', x)
print('y: \n', y)
print( y0,  x0)

x: 
 [[0.13463769 0.50095825 0.77621161 0.79324708]
 [0.08054553 0.92267489 0.15695475 0.02307288]
 [0.32542004 0.33416717 0.49432071 0.30944708]
 [0.72333571 0.24035355 0.22995808 0.53928891]
 [0.63654988 0.6426791  0.40233187 0.12294522]]
y: 
 2
0 []


In [ ]:
# Task 12:

import pandas as pd
 
df = pd.read_csv("/content/iris.csv")
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [ ]:
# Task 12:

df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df['sepal_length'].mean()

5.843333333333334

In [ ]:
df['sepal_length'].median()

5.8

In [ ]:
df['sepal_length'].std()

0.828066127977863